apiVersion: v1
kind: App
metadata:
  name: ai-knowledge-assistant
spec:
  services:
    - name: app
      source:
        git:
          repository: https://github.com/Dan-The-Xage/ai-knowledge-assistant
          branch: master
      ports:
        - port: 3000
          public: true
          protocol: http
        - port: 8000
          protocol: http
      build:
        type: docker
        dockerfile: Dockerfile
      environment:
        - name: HF_API_TOKEN
          value: ${HF_API_TOKEN}
        - name: SECRET_KEY
          value: ${SECRET_KEY}
        - name: DATABASE_URL
          value: ${DATABASE_URL}
        - name: NEXT_PUBLIC_API_URL
          value: ${KOYEB_PUBLIC_DOMAIN}
        - name: NEXT_PUBLIC_APPWRITE_PROJECT_ID
          value: ${APPWRITE_PROJECT_ID}
        - name: NEXT_PUBLIC_APP_NAME
          value: "AI Knowledge Assistant"
      regions:
        - fra
