# Koyeb configuration for frontend deployment only
apiVersion: v1
kind: App
metadata:
  name: ai-knowledge-assistant-frontend
spec:
  services:
    - name: frontend
      source:
        git:
          repository: https://github.com/Dan-The-Xage/ai-knowledge-assistant
          branch: master
          workdir: frontend
      ports:
        - port: 3000
          public: true
          protocol: http
      build:
        type: buildpack
        buildpack:
          name: nodejs
      environment:
        - name: NEXT_PUBLIC_API_URL
          value: https://backend-ai-knowledge-assistant.koyeb.app
        - name: NEXT_PUBLIC_APPWRITE_PROJECT_ID
          value: ${APPWRITE_PROJECT_ID}
        - name: NEXT_PUBLIC_APP_NAME
          value: "AI Knowledge Assistant"
      regions:
        - fra
