# Koyeb configuration for backend deployment only
apiVersion: v1
kind: App
metadata:
  name: ai-knowledge-assistant-backend
spec:
  services:
    - name: backend
      source:
        git:
          repository: https://github.com/Dan-The-Xage/ai-knowledge-assistant
          branch: master
          workdir: backend
      ports:
        - port: 8000
          public: true
          protocol: http
      build:
        type: buildpack
        buildpack:
          name: python
      environment:
        - name: DATABASE_URL
          value: ${DATABASE_URL}
        - name: SECRET_KEY
          value: ${SECRET_KEY}
        - name: HF_API_TOKEN
          value: ${HF_API_TOKEN}
        - name: LLM_MODEL_NAME
          value: mistralai/Mistral-7B-Instruct-v0.2
        - name: EMBEDDING_MODEL
          value: BAAI/bge-small-en-v1.5
        - name: DEBUG
          value: "false"
      regions:
        - fra
